### ISSUE TITLE
Please migrate to / support Python 3

### ISSUE THREAD

**Issue by rapgro** [wardi/speedometer#11]
https://docs.python.org/3/howto/pyporting.html
https://docs.python.org/2/library/2to3.html

**Comment by wardi** [comment]
I won't be working on this, but a conversion would be accepted (maybe clean up the code and make more general while we're at it)

**Comment by rapgro** [comment]
Do you have some regression tests to let ensure we don't break anything with the refactoring?

**Comment by holms** [comment]
Doesn't work on python3 :/ 

```
Romans-iMac:holms-ansible-osx holms$ sudo pip install speedometer
The directory '/Users/holms/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/holms/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting speedometer
  Downloading Speedometer-2.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-348fs4tv/speedometer/setup.py", line 26, in <module>
        import speedometer
      File "/private/tmp/pip-build-348fs4tv/speedometer/speedometer.py", line 403
        def get_data(self, (maxcol,maxrow)):
                           ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-348fs4tv/speedometer/
```

**Comment by jova2** [comment]
Hi, I believe the necessary changes are available here: https://github.com/wardi/speedometer/pull/17

**Comment by jova2** [comment]
Version 2.8-3 is now available in Debian Testing with Python3 Support

**Comment by iyzsong** [comment]
Fixed in master, close now, thank you!
