### ISSUE TITLE
Error when data is added to file

### ISSUE THREAD

**Issue by nkh** [wardi/speedometer#36]
commands:

 speedometer speedometer_test  200

touch speedometer_test
cat > speedometer_test
type type type\n
***crashes here***

Waiting for 'speedometer_test' to be created...
^[^[:Traceback (most recent call last):
  File "/usr/bin/speedometer", line 1094, in <module>
    console()
  File "/usr/bin/speedometer", line 812, in console
    do_display(cols, urwid_ui, exit_on_complete, num_colors)
  File "/usr/bin/speedometer", line 817, in do_display
    mg.main(num_colors)
  File "/usr/bin/speedometer", line 272, in main
    self.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 823, in _loop
    alarm_callback()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 173, in cb
    callback(self, user_data)
  File "/usr/bin/speedometer", line 287, in update_callback
    pending = self.update_readings()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/speedometer", line 296, in update_readings
    if d.update_readings(): pending += 1
       ^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/speedometer", line 392, in update_readings
    self.est.set_text(readable_time(e,10))
                      ^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/speedometer", line 761, in readable_time
    new_out = new_out + value + suf
              ~~~~~~~~^~~~~~~
TypeError: can only concatenate str (not "int") to str

**Comment by normanr** [comment]
Duplicate of #34
